homeassistant:
  name: Home
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 190
  unit_system: metric
  time_zone: Europe/Moscow
  
  customize: !include customize.yaml
  packages: !include_dir_merge_named includes/packages
  

logger:
  default: info
  logs:
     libav.rtsp: critical


http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.10


miio_gateway:
  host: 192.168.1.20
  port: 54321


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homekit: !include includes/homekit.yaml

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/vacuum-card/vacuum-card.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
      
device_tracker:
  - platform: padavan_tracker
    consider_home: 180
    interval_seconds: 5
    url: http://192.168.1.1:81/
    username: !secret mi3g_username
    password: !secret mi3g_password

# Text to speech
tts:
  - platform: google_translate

telegram_bot:
  - platform: polling
    api_key: !secret tg_bot_api_key
    allowed_chat_ids:
      - !secret chat_id_loskutyan

notify: !include includes/notify.yaml
timer: !include includes/timer.yaml
group: !include includes/groups.yaml
scene: !include includes/scenes.yaml
recorder: !include includes/recorder.yaml
fan: !include includes/fan.yaml

automation:  !include_dir_merge_list includes/automations
binary_sensor: !include_dir_merge_list includes/binary_sensors
script: !include_dir_merge_named includes/scripts
sensor: !include_dir_merge_list includes/sensors
switch: !include_dir_merge_list includes/switches
