homeassistant:
  name: Home
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 190
  unit_system: metric
  country: RU
  time_zone: 'Europe/Moscow'
  currency: RUB
  internal_url: !secret internal_url
  external_url: !secret external_url

  customize: !include customize.yaml
  packages: !include_dir_merge_named includes/packages


logger:
  default: info
  logs:
     libav.rtsp: critical


http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret cubeserver_ip


miio_gateway:
  host: 192.168.1.20
  port: 54321


duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_access_token


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


homekit: !include includes/homekit.yaml


lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/vacuum-card/vacuum-card.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
    - url: /hacsfiles/mini-humidifier/mini-humidifier-bundle.js
      type: module
    - url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
      type: module
    - url: /hacsfiles/lovelace-battery-entity-row/battery-entity-row.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module


# Text to speech
tts:
  - platform: google_translate


influxdb:
  host: !secret cubeserver_influxdb_host
  port: !secret cubeserver_influxdb_port
  exclude:
    entity_globs: '*'


telegram_bot:
  - platform: polling
    api_key: !secret tg_bot_api_key
    allowed_chat_ids:
      - !secret chat_id_loskutyan


smartir:
  check_updates: false


notify: !include includes/notify.yaml
recorder: !include includes/recorder.yaml
fan: !include includes/fan.yaml

binary_sensor: !include_dir_merge_list includes/binary_sensors
sensor: !include_dir_merge_list includes/sensors
