homeassistant:
  name: Home
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 190
  unit_system: metric
  time_zone: Europe/Moscow
  
  packages: !include_dir_merge_named includes/packages
  

logger:
  default: info
  logs:
     libav.rtsp: critical


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homekit:
  - port: 21170
    filter:
      include_domains:
        - vacuum
        - humidifier
      include_entities:
        - sensor.cleargrass_air_co2a
        - sensor.cleargrass_air_pm25
        - sensor.cpu_temperature

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module

# Text to speech
tts:
  - platform: google_translate

group: !include includes/groups.yaml
automation: !include includes/automations.yaml
script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml
recorder: !include includes/recorder.yaml

sensor: !include_dir_merge_list includes/sensors
