homeassistant:
  name: Home
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 190
  unit_system: metric
  time_zone: Europe/Moscow
  
  customize: !include customize.yaml
  packages: !include_dir_merge_named includes/packages
  

logger:
  default: info
  logs:
     libav.rtsp: critical


http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret cubeserver_ip


miio_gateway:
  host: 192.168.1.20
  port: 54321


weather:
  - platform: yandex_weather
    api_key: !secret yandex_dev_api_key


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


homekit: !include includes/homekit.yaml


apcupsd:
  host: !secret cubeserver_ip
  port: 3551


lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/vacuum-card/vacuum-card.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
    - url: /hacsfiles/mini-humidifier/mini-humidifier-bundle.js
      type: module


# Text to speech
tts:
  - platform: google_translate


telegram_bot:
  - platform: polling
    api_key: !secret tg_bot_api_key
    allowed_chat_ids:
      - !secret chat_id_loskutyan


home_connect:
  client_id: !secret home_connect_client_id
  client_secret: !secret home_connect_client_secret


notify: !include includes/notify.yaml
timer: !include includes/timer.yaml
group: !include includes/groups.yaml
scene: !include includes/scenes.yaml
recorder: !include includes/recorder.yaml
fan: !include includes/fan.yaml

automation:  !include_dir_merge_list includes/automations
binary_sensor: !include_dir_merge_list includes/binary_sensors
script: !include_dir_merge_named includes/scripts
sensor: !include_dir_merge_list includes/sensors
switch: !include_dir_merge_list includes/switches
