title: My Home Assistant - MiniPC
views:
  - !include lovelace/00_now.yaml
  - !include lovelace/01_bedroom.yaml
  - !include lovelace/02_kidsroom.yaml
  - !include lovelace/03_kitchen.yaml
  - !include lovelace/04_bathroom.yaml
  - !include lovelace/09_server_room.yaml
  - !include lovelace/10_climate_sensors.yaml
  - !include lovelace/20_ha_state.yaml

button_card_templates: !include lovelace_templates.yaml
