title: My Home Assistant - Raspberry Pi 3B
views:
  - !include lovelace/00_now.yaml
  - !include lovelace/01_bedroom.yaml
  - !include lovelace/02_kidsroom.yaml
  - !include lovelace/03_kitchen.yaml
  - !include lovelace/09_server_room.yaml
  - !include lovelace/10_climate_sensors.yaml
  - !include lovelace/20_ha_state.yaml
  - !include lovelace/90_weather.yaml
