tg_service:
  automation:
    - id: 'Низкий уровень заряда батарей'
      alias: telegram_low_battery_level_notify
      description: ''
      use_blueprint:
        path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
        input:
          time: '12:00:00'
          day: 2
          actions:
          - service: notify.tg_bot
            data:
              message: |
                {{'\U0001FAAB'}} Низкий заряд батарей:
                {{ sensors.split(', ')  | join('\n') }}
