- platform: template
  sensors:
    cleargrass_air_co2:
      friendly_name: 'Cleargrass air CO²'
      device_class: carbon_dioxide
      unit_of_measurement: 'ppm'
      value_template: '{{ state_attr(''air_quality.cgllc_airmonitor_s1'', ''carbon_dioxide'') }}'
      availability_template: '{{ state_attr(''air_quality.cgllc_airmonitor_s1'', ''carbon_dioxide'') | float(0) > 100 }}'
      icon_template: mdi:molecule-co2
    
    cleargrass_air_tvoc:
      friendly_name: 'Cleargrass air tVOC'
      device_class: volatile_organic_compounds
      unit_of_measurement: 'ppb'
      value_template: '{{ state_attr(''air_quality.cgllc_airmonitor_s1'', ''total_volatile_organic_compounds'') }}'
      availability_template: '{{ state_attr(''air_quality.cgllc_airmonitor_s1'', ''total_volatile_organic_compounds'') | float(0) > 1 }}'
      icon_template: mdi:atom
    
    cleargrass_air_pm25:
      friendly_name: 'Cleargrass air PM2.5'
      device_class: pm25
      unit_of_measurement: 'ppm'
      value_template: '{{ state_attr(''air_quality.cgllc_airmonitor_s1'', ''particulate_matter_2_5'') }}'
      icon_template: mdi:grain
    
    cleargrass_air_temperature:
      friendly_name: 'Cleargrass air Температура'
      device_class: temperature
      unit_of_measurement: '°C'
      value_template: '{{ state_attr(''air_quality.cgllc_airmonitor_s1'', ''temperature'') }}'
      availability_template: '{{ state_attr(''air_quality.cgllc_airmonitor_s1'', ''temperature'') | float(0) > 10 }}'
      icon_template: mdi:thermometer
    
    cleargrass_air_humidity:
      friendly_name: 'Cleargrass air Влажность'
      device_class: humidity
      unit_of_measurement: '%'
      value_template: '{{ state_attr(''air_quality.cgllc_airmonitor_s1'', ''humidity'') }}'
      availability_template: '{{ state_attr(''air_quality.cgllc_airmonitor_s1'', ''humidity'') | float(0) > 5 }}'
      icon_template: mdi:water-percent
    
    bedroom_aqara_temperature:
      friendly_name: 'Bedroom aqara Температура'
      device_class: temperature
      unit_of_measurement: '°C'
      value_template: '{{ states(''sensor.bedroom_aqara_air_sensor_temperature'') }}'
      availability_template: '{{ states(''sensor.bedroom_aqara_air_sensor_temperature'') | float(0) > 10 }}'
      icon_template: mdi:thermometer
    
    bedroom_aqara_humidity:
      friendly_name: 'Bedroom aqara Влажность'
      device_class: humidity
      unit_of_measurement: '%'
      value_template: '{{ states(''sensor.bedroom_aqara_air_sensor_humidity'') }}'
      availability_template: '{{ states(''sensor.bedroom_aqara_air_sensor_humidity'') | float(0) > 5 }}'
      icon_template: mdi:water-percent
    
    bedroom_average_temperature:
      friendly_name: 'Температура'
      device_class: temperature
      unit_of_measurement: '°C'
      value_template: >
        {% set temps = [states('sensor.cleargrass_air_temperature'),
                        states('sensor.bedroom_aqara_temperature')] %}
        {% set filtered_temps = temps | reject('equalto', 'unavailable') | map('float') | list %}
        {{ filtered_temps | sum / filtered_temps | count }}
      availability_template: >
        {% set temps = [states('sensor.cleargrass_air_temperature'),
                        states('sensor.bedroom_aqara_temperature')] %}
        {{ temps | reject('equalto', 'unavailable') | list | count == 2 }}
      icon_template: mdi:thermometer
    
    bedroom_average_humidity:
      friendly_name: 'Влажность'
      device_class: humidity
      unit_of_measurement: '%'
      value_template: >
        {% set hums = [states('sensor.cleargrass_air_humidity'),
                       states('sensor.bedroom_aqara_humidity')] %}
        {% set filtered_hums = hums | reject('equalto', 'unavailable') | map('float') | list %}
        {{ filtered_hums | sum / filtered_hums | count }}
      availability_template: >
        {% set hums = [states('sensor.cleargrass_air_humidity'),
                       states('sensor.bedroom_aqara_humidity')] %}
        {{ hums | reject('equalto', 'unavailable') | list | count == 2 }}
      icon_template: mdi:water-percent
