- platform: template
  sensors:
    cleargrass_air_co2:
      friendly_name: 'Cleargrass air CO²'
      device_class: carbon_dioxide
      unit_of_measurement: 'ppm'
      availability_template: >
        {% set value = states('sensor.cgllc_s1_04e8_co2_density') | float(0) %}
        {{ value > 0 and value < 10000 }}
      value_template: '{{ states(''sensor.cgllc_s1_04e8_co2_density'') }}'
      icon_template: mdi:molecule-co2

    cleargrass_air_tvoc:
      friendly_name: 'Cleargrass air tVOC'
      device_class: volatile_organic_compounds
      unit_of_measurement: 'ppb'
      availability_template: >
        {% set value = states('sensor.cgllc_s1_04e8_tvoc_density') | float(0) %}
        {{ value > 0 and value < 10000 }}
      value_template: '{{ states(''sensor.cgllc_s1_04e8_tvoc_density'') }}'
      icon_template: mdi:atom

    cleargrass_air_pm25:
      friendly_name: 'Cleargrass air PM2.5'
      device_class: pm25
      unit_of_measurement: 'ppm'
      availability_template: >
        {% set value = states('sensor.cgllc_s1_04e8_pm25_density') | float(-1) %}
        {{ value >= 0 and value < 1000 }}
      value_template: '{{ states(''sensor.cgllc_s1_04e8_pm25_density'') }}'
      icon_template: mdi:molecule

    cleargrass_air_temperature:
      friendly_name: 'Cleargrass air Температура'
      device_class: temperature
      unit_of_measurement: '°C'
      availability_template: >
        {% set value = states('sensor.cgllc_s1_04e8_temperature') | float(0) %}
        {{ value > 0 and value < 100 }}
      value_template: '{{ states(''sensor.cgllc_s1_04e8_temperature'') }}'

    cleargrass_air_humidity:
      friendly_name: 'Cleargrass air Влажность'
      device_class: humidity
      unit_of_measurement: '%'
      availability_template: >
        {% set value = states('sensor.cgllc_s1_04e8_environment') | float(0) %}
        {{ value > 0 and value < 100 }}
      value_template: '{{ states(''sensor.cgllc_s1_04e8_environment'') }}'

    bedroom_aqara_temperature:
      friendly_name: 'Bedroom aqara Температура'
      device_class: temperature
      unit_of_measurement: '°C'
      value_template: '{{ states(''sensor.bedroom_aqara_air_sensor_temperature'') }}'
      availability_template: >
        {% set value = states('sensor.bedroom_aqara_air_sensor_temperature') | float(0) %}
        {{ value > 10 and value < 100 }}

    bedroom_aqara_humidity:
      friendly_name: 'Bedroom aqara Влажность'
      device_class: humidity
      unit_of_measurement: '%'
      value_template: '{{ states(''sensor.bedroom_aqara_air_sensor_humidity'') }}'
      availability_template: >
        {% set value = states('sensor.bedroom_aqara_air_sensor_humidity') | float(0) %}
        {{ value > 5 and value < 100 }}
  
    bedroom_average_temperature:
      friendly_name: 'Температура'
      device_class: temperature
      unit_of_measurement: '°C'
      value_template: >
        {% set temps = [states('sensor.cleargrass_air_temperature'),
                        states('sensor.bedroom_aqara_temperature')] %}
        {% set filtered_temps = temps | reject('equalto', 'unavailable') | map('float') | list %}
        {{ filtered_temps | sum / filtered_temps | count }}
      availability_template: >
        {% set temps = [states('sensor.cleargrass_air_temperature'),
                        states('sensor.bedroom_aqara_temperature')] %}
        {{ temps | reject('equalto', 'unavailable') | list | count == 2 }}

    bedroom_average_humidity:
      friendly_name: 'Влажность'
      device_class: humidity
      unit_of_measurement: '%'
      value_template: >
        {% set hums = [states('sensor.cleargrass_air_humidity'),
                       states('sensor.bedroom_aqara_humidity')] %}
        {% set filtered_hums = hums | reject('equalto', 'unavailable') | map('float') | list %}
        {{ filtered_hums | sum / filtered_hums | count }}
      availability_template: >
        {% set hums = [states('sensor.cleargrass_air_humidity'),
                       states('sensor.bedroom_aqara_humidity')] %}
        {{ hums | reject('equalto', 'unavailable') | list | count == 2 }}
