- platform: template
  sensors:
    qingping_air_lite_co2:
      friendly_name: 'Qingping air lite CO²'
      device_class: carbon_dioxide
      unit_of_measurement: 'ppm'
      value_template: "{{ state_attr('sensor.cgllc_cgdn1_a7b6_environment', 'environment.co2_density') }}"
      availability_template: "{{ state_attr('sensor.cgllc_cgdn1_a7b6_environment', 'environment.co2_density') | float(0) > 100 }}"
      icon_template: mdi:molecule-co2

    qingping_air_lite_pm25:
      friendly_name: 'Qingping air lite PM2.5'
      device_class: pm25
      unit_of_measurement: 'µg/m³'
      value_template: "{{ state_attr('sensor.cgllc_cgdn1_a7b6_environment', 'environment.pm2_5_density') }}"
      icon_template: mdi:molecule

    qingping_air_lite_pm10:
      friendly_name: 'Qingping air lite PM10'
      device_class: pm10
      unit_of_measurement: 'µg/m³'
      value_template: "{{ state_attr('sensor.cgllc_cgdn1_a7b6_environment', 'environment.pm10_density') }}"
      icon_template: mdi:grain

    qingping_air_lite_temperature:
      friendly_name: 'Qingping air lite Температура'
      device_class: temperature
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('sensor.cgllc_cgdn1_a7b6_environment', 'environment.temperature') }}"
      availability_template: "{{ state_attr('sensor.cgllc_cgdn1_a7b6_environment', 'environment.temperature') | float(0) > 10 }}"

    qingping_air_lite_humidity:
      friendly_name: 'Qingping air lite Влажность'
      device_class: humidity
      unit_of_measurement: '%'
      value_template: "{{ state_attr('sensor.cgllc_cgdn1_a7b6_environment', 'environment.relative_humidity') }}"
      availability_template: "{{ state_attr('sensor.cgllc_cgdn1_a7b6_environment', 'environment.relative_humidity') | float(0) > 5 }}"

    kidsroom_aqara_temperature:
      friendly_name: 'Kidsroom Aqara Температура'
      device_class: temperature
      unit_of_measurement: '°C'
      value_template: "{{ states('sensor.kidsroom_aqara_air_sensor_temperature') }}"
      availability_template: "{{ states('sensor.kidsroom_aqara_air_sensor_temperature') | float(0) > 10 }}"

    kidsroom_aqara_humidity:
      friendly_name: 'Kidsroom Aqara Влажность'
      device_class: humidity
      unit_of_measurement: '%'
      value_template: "{{ states('sensor.kidsroom_aqara_air_sensor_humidity') }}"
      availability_template: "{{ states('sensor.kidsroom_aqara_air_sensor_humidity') | float(0) > 5 }}"

    kidsroom_average_temperature:
      friendly_name: 'Температура'
      device_class: temperature
      unit_of_measurement: '°C'
      value_template: >
        {% set temps = [states('sensor.kidsroom_aqara_temperature')] %}
        {% set filtered_temps = temps | reject('equalto', 'unavailable') | map('float') | list %}
        {{ filtered_temps | sum / filtered_temps | count }}
      availability_template: >
        {% set temps = [states('sensor.kidsroom_aqara_temperature')] %}
        {{ temps | reject('equalto', 'unavailable') | list | count > 0 }}

    kidsroom_average_humidity:
      friendly_name: 'Влажность'
      device_class: humidity
      unit_of_measurement: '%'
      value_template: >
        {% set hums = [states('sensor.qingping_air_lite_humidity'),
                       states('sensor.kidsroom_aqara_humidity')] %}
        {% set filtered_hums = hums | reject('equalto', 'unavailable') | map('float') | list %}
        {{ filtered_hums | sum / filtered_hums | count }}
      availability_template: >
        {% set hums = [states('sensor.qingping_air_lite_humidity'),
                       states('sensor.kidsroom_aqara_humidity')] %}
        {{ hums | reject('equalto', 'unavailable') | list | count == 2 }}
