- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'time_date'

- platform: template
  sensors:
    weekday:
      value_template: >
        {{ ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'][now().weekday()] }}

    electricity_price:
      value_template: '6.15'
      unit_of_measurement: 'RUB/kWh'
