- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'time_date'
    
- platform: template
  sensors:
    sun_next_rising:
      friendly_name: 'Подъем солнца'
      value_template: >
        {% if state_attr('sun.sun', 'elevation') | float < 0 %}
          {{ state_attr('sun.sun', 'next_rising') }}
        {% else %}
          unavailable
        {% endif %}
    sun_next_setting:
      friendly_name: 'Заход солнца'
      value_template: >
        {% if state_attr('sun.sun', 'elevation') | float >= 0 %}
          {{ state_attr('sun.sun', 'next_setting') }}
        {% else %}
          unavailable
        {% endif %}
