- platform: template
  sensors:
    phone_mac_address:
      friendly_name: 'MAC-адрес моего телефона'
      value_template: '22_66_d6_ed_b9_ca'

    sisters_phone_mac_address:
      friendly_name: 'MAC-адрес телефона Кати'
      value_template: 'e6_c8_8d_97_17_8a'

    sons_phone_mac_address:
      friendly_name: 'MAC-адрес телефона Коли'
      value_template: '00_24_36_2a_73_8b'
