- platform: template
  sensors:
    phone_mac_address:
      friendly_name: 'MAC-адрес телефона'
      value_template: '98_60_ca_d9_a5_02'


- platform: apcupsd
  resources:
    - bcharge
    - loadpct
    - status
    - timeleft
    - model
    - linev
    - outputv
