- platform: systemmonitor
  resources:
    - type: processor_use
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: last_boot
    - type: disk_free
      arg: /

- platform: command_line
  name: 'CPU Temperature'
  unit_of_measurement: '°C'
  command: 'cat /sys/class/thermal/thermal_zone0/temp'
  value_template: '{{ value | multiply(0.001) | round(1) }}'
