- platform: systemmonitor
  resources:
    - type: processor_use
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: last_boot
    - type: disk_free
      arg: /

- platform: command_line
  name: CPU Temperature
  unit_of_measurement: '°C'
  command: 'cat /sys/class/thermal/thermal_zone0/temp'
  # If errors occur, make sure configuration file is encoded as UTF-8
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: command_line
  name: GPU Temperature
  unit_of_measurement: '°C'
  command: '/opt/vc/bin/vcgencmd measure_temp | cut -c6- | rev | cut -c3- | rev'
  # If errors occur, make sure configuration file is encoded as UTF-8
  value_template: '{{ value }}'

- platform: sql
  db_url: mysql://homeassistant:homeassistant@core-mariadb/homeassistant?charset=utf8
  queries:
    - name: Maria DB size
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1048576, 2) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: 'value'
      unit_of_measurement: MB
