- platform: template
  sensors:
    vacuum_main_brush_left:
      friendly_name: 'Roborock S5 Max Часов уборки до замены основной щетки'
      value_template: "{{ state_attr('vacuum.roborock_vacuum_s5e', 'main_brush_left') | float }}"
      availability_template: "{{ state_attr('vacuum.roborock_vacuum_s5e', 'main_brush_left') | float > 0 }}"
      icon_template: mdi:robot-vacuum
    
    vacuum_side_brush_left:
      friendly_name: 'Roborock S5 Max Часов уборки до замены боковой щетки'
      value_template: "{{ state_attr('vacuum.roborock_vacuum_s5e', 'side_brush_left') | float }}"
      availability_template: "{{ state_attr('vacuum.roborock_vacuum_s5e', 'side_brush_left') | float > 0 }}"
      icon_template: mdi:robot-vacuum
    
    vacuum_filter_left:
      friendly_name: 'Roborock S5 Max Часов уборки до замены фильтра'
      value_template: "{{ state_attr('vacuum.roborock_vacuum_s5e', 'filter_left') | float }}"
      availability_template: "{{ state_attr('vacuum.roborock_vacuum_s5e', 'filter_left') | float > 0 }}"
      icon_template: mdi:air-filter
