- platform: xiaomi_miio_airpurifier
  name: mijia_airpurifier_bedroom
  host: !secret bedroom_airpurifier_host
  token: !secret bedroom_airpurifier_token
  model: dmaker.airfresh.a1

- platform: xiaomi_miio_airpurifier
  name: mijia_airpurifier_kidsroom
  host: !secret kidsroom_airpurifier_host
  token: !secret kidsroom_airpurifier_token
  model: dmaker.airfresh.a1
