- platform: xiaomi_miio_airpurifier
  name: mijia_airpurifier_bedroom
  host: 192.168.1.76
  token: 50b486f69aa3b0c6af71f7db7f8f8b97
  model: dmaker.airfresh.a1
  
- platform: xiaomi_miio_airpurifier
  name: mijia_airpurifier_kidsroom
  host: 192.168.1.77
  token: 0c4f2780671ac1ec7dc0642bdeb8a53c
  model: dmaker.airfresh.a1
